kind: Service
apiVersion: v1

metadata:
  name: rabbitmq
  namespace: monsoon3
  labels:
    system: openstack
    component: messaging
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{cluster_config['rabbitmq.port.metrics']}}"
spec:
  type: NodePort
  selector:
    name: rabbitmq

  ports: 
    - name: rabbitmq
      port: {{cluster_config['rabbitmq.port.public']}}
    - name: rabbitmq-mgmt
      port: {{cluster_config['rabbitmq.port.management']}}
