# The region for which all metrics passing through this server will be persisted
region: {{cluster_config['os_region_name']}}

# Maximum rows (Mysql) or points (Influxdb) to return when listing elements
maxQueryLimit: 10000

# Whether this server is running on a secure port
accessedViaHttps: false

# Topic for publishing metrics to
metricsTopic: metrics

# Topic for publishing domain events to
eventsTopic: events

validNotificationPeriods:
  - 60

kafka:
  brokerUris: ["{{cluster_config['monasca_kafka_cluster_urls']}}"]
  zookeeperUris: ["{{cluster_config['monasca_zookeeper_cluster_urls']}}"]
  healthCheckTopic: healthcheck

mysql:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://{{cluster_config['monasca_mysql_endpoint_host_internal']}}:{{cluster_config['monasca_mysql_port_internal']}}/mon?connectTimeout=5000&autoReconnect=true
  user: monapi
  password: {{cluster_config['monasca_mysql_monapi_password']}}
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 4
  maxSize: 32
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true

databaseConfiguration:
#vertica | influxdb
  databaseType: influxdb

#Uncomment if databaseType is influxDB
influxDB:
  version: V9
  name: mon
  replicationFactor: 1
  url: http://{{cluster_config['monasca_influxdb_endpoint_host_internal']}}:8086
  user: mon_api
  password: {{cluster_config['monasca_influxdb_monapi_password']}}
  retentionPolicy:
  maxHttpConnections: 100
  gzip: true

# unused but monasca_api insists on this section
vertica:
  driverClass: com.vertica.jdbc.Driver
  url: jdbc:vertica://192.168.10.8/mon
  user: dbadmin
  password: password
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 4
  maxSize: 32
  checkConnectionWhileIdle: false

middleware:
  enabled: true
  #serviceIds: 100
  #endpointIds: 160
  serverVIP: {{cluster_config['keystone_api_endpoint_host_internal']}}
  serverPort: {{cluster_config['keystone_api_port_internal']}}
  connTimeout: 5000                         # milliseconds!!
  useHttps: KEYSTONE_SSL
  #connSSLClientAuth: true
  #keystore: etc/monasca/keystore.jks
  #keystorePass: changeit
  truststore: /etc/ssl/certs/java/cacerts
  truststorePassword: changeit
  connPoolMaxActive: 3
  connPoolMaxIdle: 3
  connPoolEvictPeriod: 600000
  connPoolMinIdleTime: 600000
  connRetryTimes: 3
  connRetryInterval: 50                     # seconds
  defaultAuthorizedRoles: [monasca-user]    # restricted in order to control adoption, might change to admin
  agentAuthorizedRoles: [monasca-agent]
  adminAuthMethod: password
  adminUser: {{cluster_config['monasca_api_username']}}
  adminPassword: {{cluster_config['monasca_api_password']}}
  adminProjectName: {{cluster_config['monasca_api_project_name']}}
  adminUserDomainName: {{cluster_config['monasca_api_project_domain_name']}}
  adminProjectDomainName: {{cluster_config['monasca_api_project_domain_name']}}
  adminToken: unused
  timeToCacheToken: 3600               # wait max. 1h until added/removed role take effect
  maxTokenCacheSize: 1048576

server:
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 0.0.0.0            # bind to all interfaces (127.0.0.1 will not work in K8s)
      maxRequestHeaderSize: 16KiB  # Allow large headers used by keystone tokens
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 0.0.0.0            # bind to all interfaces (127.0.0.1 will not work in K8s)
  requestLog:
   timeZone: UTC
   appenders:
    - type: file
      currentLogFilename: "/var/log/monasca/api/request.log"
      threshold: WARN
      archive: true
      archivedLogFilenamePattern: "/var/log/monasca/api/request-%d.log.gz"
      archivedFileCount: 5

# DropWizard metrics settings
metrics:
  frequency: 1 minute

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: WARN

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.example.app: WARN

  appenders:
    - type: console
      threshold: WARN
      timeZone: UTC
      target: stdout
      logFormat: # TODO

#    - type: file
      #currentLogFilename: ./log/monasca-api.log
#      currentLogFilename: /var/log/monasca/api/monasca-api.log
#      threshold: WARN
#      archive: true
#      #archivedLogFilenamePattern: ./log/monasca-api-%d.log
#      archivedLogFilenamePattern: /var/log/monasca/api/monasca-api-%d.log
#      archivedFileCount: 5
#      timeZone: UTC
#      logFormat: # TODO
#
#    - type: syslog
#      host: localhost
#      port: 514
#      facility: local0
#      threshold: WARN
#      logFormat: # TODO
