kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: keystone
  namespace: monsoon3
  labels:
    system: openstack
    component: keystone
  annotations:
    kubernetes.io/change-cause: {{cluster_config['cluster.deployment.reason']}}
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      name: keystone
  template:
    metadata:
      labels:
        name: keystone
      annotations:
        checksum/keystone.etc: {{checksums['keystone-etc-configmap.yaml']}}
        checksum/keystone.bin: {{checksums['keystone-bin-configmap.yaml']}}
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: keystone
          image: {{cluster_config['cluster.image.repository']}}/{{cluster_config['cluster.image.namespace']}}/ubuntu-source-keystone-m3:{{cluster_config['image.version.keystone.m3']}}
          imagePullPolicy: IfNotPresent
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - keystone-start
          livenessProbe:
            httpGet:
              path: /v3
              port: 5000
            initialDelaySeconds: 15
            timeoutSeconds: 15
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: keystone.sentry.dsn
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
          ports:
            - name: public
              containerPort: 5000
            - name: admin
              containerPort: 35357
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /keystone-etc
              name: keystone-etc
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
            - mountPath: /container.init
              name: container-init
        - name: statsd
          image: prom/statsd-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{cluster_config['keystone.port.metrics']}}
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: keystone-etc
          configMap:
            name: keystone-etc
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
        - name: container-init
          configMap:
            name: keystone-bin