kind: DaemonSet
apiVersion: extensions/v1beta1

metadata:
  name: monasca-fluent
  namespace: monasca

spec:
  template:
    metadata:
      labels:
        component: monasca-fluent
    spec:
      containers:
        - name: monasca-fluent
          image: docker.mo.sap.corp/monasca/monasca-fluent:latest
          imagePullPolicy: Always
          command:
            - /openstack-kube/openstack-kube/scripts/monasca-fluent_start
          resources:
#            limits:
#              cpu: 1000m
#              memory: 2000Mi
          env:
            - name: FLUENTD_ARGS
              value: -q
            - name: ELASTICSEARCH_HOST
              value: "monasca-elasticsearch-client"
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          ports: 
            - containerPort: 8885
              hostPort: 8885
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers

