kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: neutron-cisco-asr
  namespace: monsoon3
  labels:
    system: openstack
    component: neutron
  annotations:
    kubernetes.io/change-cause: {{cluster_config['cluster.deployment.reason']}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: neutron-cisco-asr
  template:
    metadata:
      labels:
        name: neutron-cisco-asr
      annotations:
        pod.beta.kubernetes.io/hostname:  asr-pet
        checksum/neutron.etc: {{checksums['neutron-etc-configmap.yaml']}}
        checksum/neutron.bin: {{checksums['neutron-bin-configmap.yaml']}}
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: neutron-cisco-asr
          image: {{cluster_config['cluster.image.repository']}}/{{cluster_config['cluster.image.namespace']}}/ubuntu-source-neutron-server-m3:{{cluster_config['image.version.neutron.server.m3']}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - neutron-asr-start
          env:
            - name: DEBUG_CONTAINER
              value: "false"
          livenessProbe:
            exec:
              command:
              - /openstack-kube/openstack-kube/scripts/liveness-checks/neutron/service-liveness-check
              - --config-file=/etc/neutron/neutron.conf
              - --config-file=/openstack-kube/openstack-kube/scripts/liveness-checks/neutron/cisco-cfg-agent-liveness.conf
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 2
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
            - mountPath: /neutron-etc
              name: neutron-etc
            - mountPath: /cisco-patches
              name: cisco-patches
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: neutron-etc
          configMap:
            name: neutron-etc
        - name: cisco-patches
          configMap:
            name: cisco-patches
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
        - name: container-init
          configMap:
            name: neutron-bin

