apiVersion: v1
kind: ReplicationController
metadata:
  name: monasca-es-client
  namespace: monasca
  labels:
    system: openstack
    service: monitoring
    component: elasticsearch-client
spec:
  replicas: 5
  template:
    metadata:
      labels:
        component: elasticsearch-client
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: storage
          emptyDir: {}
        - name: openstack-kube
          gitRepo:
            repository: https://github.wdf.sap.corp/monsoon/openstack-kube.git
            revision: master
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
      containers:
      - name: monasca-es-client
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: docker.mo.sap.corp/monasca/monasca-elasticsearch:latest
        imagePullPolicy: Always
        command:
          - dumb-init
        args:
          - /openstack-kube/openstack-kube/scripts/monasca-elasticsearch_start
        volumeMounts:
          - mountPath: /openstack-kube
            name: openstack-kube
          - mountPath: /cluster-config
            name: cluster-config
          - mountPath: /cluster-secret
            name: cluster-secret
          - mountPath: /data
            name: storage
        env:
        - name: KUBERNETES_CA_CERTIFICATE_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "monascaelasticsearch"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        ports:
          - containerPort: {{cluster_config['monasca.elasticsearch.port.cluster']}}
            name: transport
            protocol: TCP
          - containerPort: {{cluster_config['monasca.elasticsearch.port.http']}}
            name: http
            protocol: TCP
          - name: dummymasterport
            hostPort: {{cluster_config['monasca.elasticsearch.client.dummy.port']}}
            containerPort: {{cluster_config['monasca.elasticsearch.client.dummy.port']}}
      - name: monasca-agent-forwarder
        image: docker.mo.sap.corp/monasca/monasca-agent:latest
        imagePullPolicy: Always
        command:
          - dumb-init
        args:
          - /openstack-kube/openstack-kube/scripts/monasca/agent-forwarder_start
        ports:
          - containerPort:  {{cluster_config['monasca.agent.port.forwarder']}}
        volumeMounts:
          - mountPath: /openstack-kube
            name: openstack-kube
          - mountPath: /cluster-config
            name: cluster-config
          - mountPath: /cluster-secret
            name: cluster-secret
      - name: monasca-agent-collector
        image: docker.mo.sap.corp/monasca/monasca-agent:latest
        imagePullPolicy: Always
        command:
          - dumb-init
        args:
          - /openstack-kube/openstack-kube/scripts/monasca/elasticsearch-agent-collector_start
        volumeMounts:
          - mountPath: /openstack-kube
            name: openstack-kube
          - mountPath: /cluster-config
            name: cluster-config
          - mountPath: /cluster-secret
            name: cluster-secret
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
