apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: monasca-es-client
  namespace: monasca

spec:
  tls:
     - secretName: tls-{{cluster_config['monasca.elasticsearch.endpoint.host.public'].replace(".","-")}}
       hosts: [{{cluster_config['monasca.elasticsearch.endpoint.host.public']}}]
  rules:
    - host: {{cluster_config['monasca.elasticsearch.endpoint.host.public']}}
      http:
        paths:
        - path: /
          backend:
            serviceName: monasca-es-client
            servicePort: {{cluster_config['monasca.elasticsearch.port.http']}}
