apiVersion: v1
kind: Service
metadata:
  name: monasca-es-client
  namespace: monasca
  labels:
    system: openstack
    service: monitoring
    component: elasticsearch-client
spec:
  type: LoadBalancer
  selector:
    component: elasticsearch-client
  ports:
  - name: http
    port: {{cluster_config['monasca.elasticsearch.port.http']}}
