kind: ReplicationController
apiVersion: v1

metadata:
  name: monasca-influxdb
  namespace: monasca
  labels:
    system: openstack
    service: monitoring

spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: monasca-influxdb
    spec:
      nodeSelector:
        zone: farm
      terminationGracePeriodSeconds: 600
      volumes:
        - name: monasca-influxdb-persistent-storage
          persistentVolumeClaim:
            claimName: monasca-influxdb-pvclaim
#          emptyDir: {}
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
      containers:
        - name: monasca-influxdb
          image: docker.mo.sap.corp/monasca/monasca-influxdb:latest
          imagePullPolicy: Always
#          securityContext:
#            privileged: true
          command:
            - dumb-init
          args:
            - /openstack-kube/openstack-kube/scripts/monasca/influxdb_start
          ports:
            - name: influxdb
              containerPort: {{cluster_config['monasca.influxdb.port.public']}}
            - name: influxdbadmin
              containerPort: {{cluster_config['monasca.influxdb.port.admin']}}
          volumeMounts:
            - name: monasca-influxdb-persistent-storage
              mountPath: /var/opt/influxdb
              readOnly: false
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
          lifecycle:
            preStop:
              exec:
                command: ["/openstack-kube/openstack-kube/scripts/monasca/influxdb_stop"]
          livenessProbe:
            exec:
              command:
              - /openstack-kube/openstack-kube/scripts/monasca/influxdb_liveness
            timeoutSeconds: 30
            initialDelaySeconds: 120
