---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hypervisor-kvm
  labels:
    system: openstack
    component: configuration

data:
  hypervisor.conf: |
    {{config['nova/hypervisor-kvm.conf']}}
  
