---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hypervisor-ironic
  labels:
    system: openstack
    component: configuration

data:
  hypervisor.conf: |
    {{config['nova/hypervisor-ironic.conf']}}
