---
apiVersion: v1
kind: ConfigMap
metadata:
  name: horizon-bin
  labels:
    system: openstack
    component: configuration

data:
  horizon-start: |
    {{config['horizon/horizon-start']}}
  common.sh: |
    {{config['common.sh']}}


