kind: ReplicationController
apiVersion: v1

metadata:
  name: monasca-grafana
  namespace: monasca
  labels:
    system: openstack
    service: monitoring

spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: monasca-grafana
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: monasca-grafana-persistent-storage
          persistentVolumeClaim:
            claimName: monasca-grafana-pvclaim
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: monasca-content
          gitRepo:
            repository: https://github.wdf.sap.corp/monsoon/monasca-content
            revision: master
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
      containers:
        - name: monasca-grafana
          image: docker.mo.sap.corp/monasca/monasca-grafana:latest
          imagePullPolicy: Always
          command:
            - dumb-init
          args:
            - /openstack-kube/openstack-kube/scripts/monasca/grafana_start
          ports:
            - name: nodejs
              containerPort: {{cluster_config['monasca.grafana.port.public']}}
          volumeMounts:
            - name: monasca-grafana-persistent-storage
              mountPath: /var/lib/grafana
              readOnly: false
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /monasca-content
              name: monasca-content
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret

