kind: ReplicationController
apiVersion: v1

metadata:
  name: monasca-api
  namespace: monasca
  labels:
    system: openstack
    service: monitoring

spec:
  replicas: 2
  template:
    metadata:
      labels:
        component: monasca-api
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
      containers:
        - name: monasca-api
          image: docker.mo.sap.corp/monasca/monasca-api:latest
          imagePullPolicy: Always
#          securityContext:
#            privileged: true
          command:
            - dumb-init
          args:
            - /openstack-kube/openstack-kube/scripts/monasca/api_start
          ports:
            - name: api
              containerPort: {{cluster_config['monasca.api.port.internal']}}
            - name: apiadmin
              containerPort: {{cluster_config['monasca.api.port.admin']}}
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
#          livenessProbe:
#            exec:
#              command:
#              - /openstack-kube/openstack-kube/scripts/monasca-api_health
#            timeoutSeconds: 30
#            initialDelaySeconds: 120
