kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: cinder-scheduler
  namespace: monsoon3
  labels:
    system: openstack
    component: cinder
  annotations:
    kubernetes.io/change-cause: {{cluster_config['cluster.deployment.reason']}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: cinder-scheduler
  template:
    metadata:
      labels:
        name: cinder-scheduler
      annotations:
          checksum/cinder.etc: {{checksums['cinder-etc-configmap.yaml']}}
          checksum/cinder.bin: {{checksums['cinder-bin-configmap.yaml']}}
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: cinder-scheduler
          image: {{cluster_config['cluster.image.repository']}}/{{cluster_config['cluster.image.namespace']}}/ubuntu-source-cinder-scheduler:{{cluster_config['image.version.kolla.base']}}
          imagePullPolicy: IfNotPresent
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - cinder-scheduler-start
          livenessProbe:
            exec:
              command:
              - /openstack-kube/openstack-kube/scripts/liveness-checks/cinder/service-liveness-check
              - --config-file=/etc/cinder/cinder.conf
              - --config-file=/openstack-kube/openstack-kube/scripts/liveness-checks/cinder/scheduler-liveness.conf
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 2
          volumeMounts:
            - mountPath: /development
              name: development
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /cinder-etc
              name: cinder-etc
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cinder-etc
          configMap:
            name: cinder-etc
        - name: cluster-secret
          secret:
            secretName: cluster-secret
        - name: development
          persistentVolumeClaim:
            claimName: development-pvclaim
        - name: container-init
          configMap:
            name: cinder-bin
