kind: ReplicationController
apiVersion: v1

metadata:
  name: operations
  namespace: documentation

spec:
  replicas: 2
  selector:
    name: operations
  template:
    metadata:
      labels:
        name: operations
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: www
          image: docker.mo.sap.corp/monsoon/cc-ops-documentation-ui:build.latest
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 120
            initialDelaySeconds: 30