kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: designate-central
  namespace: monsoon3
  labels:
    system: openstack
    component: designate
  annotations:
    kubernetes.io/change-cause: {{cluster_config['cluster.deployment.reason']}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      app: designate-central
  template:
    metadata:
      labels:
        app: designate-central
      annotations:
        checksum/designate.etc: {{checksums['designate-etc-configmap.yaml']}}
        checksum/designate.bin: {{checksums['designate-bin-configmap.yaml']}}

    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: designate-central
          image: {{cluster_config['cluster.image.repository']}}/{{cluster_config['cluster.image.namespace']}}/ubuntu-source-designate-central-m3:{{cluster_config['image.version.designate.central.m3']}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - designate-central-start

#          ports:
#            - name: designate-central
#              containerPort: {{cluster_config['designate.central.port.public']}}
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
            - mountPath: /designate-etc
              name: designate-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
        - name: designate-etc
          configMap:
            name: designate-etc
        - name: container-init
          configMap:
            name: designate-bin

