kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: nova-api
  namespace: monsoon3
  labels:
    system: openstack
    component: nova
  annotations:
    kubernetes.io/change-cause: {{cluster_config['cluster.deployment.reason']}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: nova-api
  template:
    metadata:
      labels:
        name: nova-api
      annotations:
        checksum/nova.etc: {{checksums['nova-etc-configmap.yaml']}}
        checksum/nova.bin: {{checksums['nova-bin-configmap.yaml']}}
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: nova-api
          image: {{cluster_config['cluster.image.repository']}}/{{cluster_config['cluster.image.namespace']}}/ubuntu-source-nova-api-m3:{{cluster_config['image.version.nova.api.m3']}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - nova-api-start
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: nova.sentry.dsn
          livenessProbe:
            httpGet:
              path: /
              port: {{cluster_config['nova.api.port.internal']}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - name: nova-api
              containerPort: {{cluster_config['nova.api.port.internal']}}
            - name: nova-metdata
              containerPort: {{cluster_config['nova.metadata.port.internal']}}
          volumeMounts:
            - mountPath: /development
              name: development
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
            - mountPath: /nova-etc
              name: nova-etc
            - mountPath: /container.init
              name: container-init

        - name: statsd
          image: prom/statsd-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{cluster_config['nova.port.metrics']}}
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
        - name: nova-etc
          configMap:
            name: nova-etc
        - name: development
          persistentVolumeClaim:
            claimName: development-pvclaim
        - name: container-init
          configMap:
            name: nova-bin