kind: Service
apiVersion: v1
metadata:
  name: monasca-storm-thresh
  namespace: monasca
  labels:
    system: openstack
    service: monitoring
spec:
  ports:
    - name: stormthresh
      port: 8000
    - name: strmthrshadmin
      port: 8088
  selector:
    component: monasca-storm-thresh

