---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-glance
  labels:
    system: openstack
    component: configuration

data:
  db-init.sh: |
    #!/usr/bin/env bash

    data_dir=/postgresql-data/data

    if [[ ! -e $data_dir ]]
    then
      mkdir $data_dir
    fi

    cp /openstack-kube/openstack-kube/etc/postgres/postgresql.conf  $data_dir/postgresql.conf


    . /openstack-kube/openstack-kube/scripts/common

    export PGUSER=postgres
    psql <<- EOSQL
        CREATE DATABASE $GLANCE_DB_NAME;
        CREATE ROLE $GLANCE_DB_USER WITH ENCRYPTED PASSWORD '$GLANCE_DB_PASSWORD' LOGIN;
        GRANT ALL PRIVILEGES ON DATABASE $GLANCE_DB_NAME TO $GLANCE_DB_USER;
    EOSQL



