kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: barbican-api
  namespace: monsoon3
  labels:
    system: openstack
    component: barbican
  annotations:
    kubernetes.io/change-cause: {{cluster_config['cluster.deployment.reason']}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: barbican-api
  template:
    metadata:
      labels:
        name: barbican-api
      annotations:
          checksum/barbican.etc: {{checksums['barbican-etc-configmap.yaml']}}
          checksum/barbican.bin: {{checksums['barbican-bin-configmap.yaml']}}
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: barbican-api
          image: {{cluster_config['cluster.image.repository']}}/{{cluster_config['cluster.image.namespace']}}/ubuntu-source-barbican-m3:{{cluster_config['image.version.barbican.api.m3']}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - barbican-api-start
#          livenessProbe:
#            httpGet:
#              path: /
#              port: {{cluster_config['barbican.api.port.internal']}}
#            initialDelaySeconds: 15
#            timeoutSeconds: 5
          ports:
            - name: barbican-api
              containerPort: {{cluster_config['barbican.api.port.internal']}}
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
            - mountPath: /barbican-etc
              name: barbican-etc
            - mountPath: /barbican-patches
              name: barbican-patches
            - mountPath: /container.init
              name: container-init

      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: barbican-etc
          configMap:
            name: barbican-etc
        - name: barbican-patches
          configMap:
            name: barbican-patches
        - name: cluster-secret
          secret:
            secretName: cluster-secret
        - name: container-init
          configMap:
            name: barbican-bin