kind: Service
apiVersion: v1

metadata:
  name: barbican-api
  namespace: monsoon3
  labels:
    system: openstack
    component: barbican
spec:
  type: NodePort
  selector:
    name: barbican-api
  ports:
    - name: barbican-api
      port: {{cluster_config['barbican.api.port.internal']}}
