---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manila-bin
  labels:
    system: openstack
    component: configuration

data:
  manila-api-start: |
    {{config['manila/manila-api-start']}}
  manila-scheduler-start: |
    {{config['manila/manila-scheduler-start']}}
  manila-share-start: |
    {{config['manila/manila-share-start']}}
  common.sh: |
    {{config['common.sh']}}


