---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cisco-patches
  labels:
    system: openstack
    component: configuration

data:
  53f08de0523f-neutron-routers-in-cisco-devices.diff: |
    {{config['mitaka/cisco/53f08de0523f_neutron_routers_in_cisco_devices.diff']}}
  device-status.diff: |
    {{config['mitaka/cisco/device_status.diff']}}
  hosting-device-manager-db.diff: |
    {{config['mitaka/cisco/hosting_device_manager_db.diff']}}
  hw-vlan-trunking-driver.diff: |
    {{config['mitaka/cisco/hw_vlan_trunking_driver.diff']}}
  l3-router-hosting-device-scheduler.diff: |
    {{config['mitaka/cisco/l3_router_hosting_device_scheduler.diff']}}

