kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: ironic-api
  namespace: monsoon3
  labels:
    system: openstack
    component: ironic
  annotations:
    kubernetes.io/change-cause: {{cluster_config['cluster.deployment.reason']}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: ironic-api
  template:
    metadata:
      labels:
        name: ironic-api
      annotations:
        checksum/ironic.etc: {{checksums['ironic-etc-configmap.yaml']}}
        checksum/ironic.bin: {{checksums['ironic-bin-configmap.yaml']}}
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: ironic-api
          image: {{cluster_config['cluster.image.repository']}}/{{cluster_config['cluster.image.namespace']}}/ubuntu-source-ironic-api:{{cluster_config['image.version.kolla.base']}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - ironic-api-start
          livenessProbe:
            httpGet:
              path: /
              port: {{cluster_config['ironic.api.port.internal']}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - name: ironic-api
              containerPort: {{cluster_config['ironic.api.port.internal']}}
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /ironic-etc
              name: ironic-etc
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
        - name: ironic-etc
          configMap:
            name: ironic-etc
        - name: container-init
          configMap:
            name: ironic-bin
