apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: ironic-api
  namespace: monsoon3
  labels:
    system: openstack
    component: ironic
spec:
  tls:
     - secretName: tls-{{cluster_config['ironic.api.endpoint.host.public'].replace(".","-")}}
       hosts: [{{cluster_config['ironic.api.endpoint.host.public']}}]
  rules:
    - host: {{cluster_config['ironic.api.endpoint.host.public']}}
      http:
        paths:
        - path: /
          backend:
            serviceName: ironic-api
            servicePort: {{cluster_config['ironic.api.port.internal']}}
