kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: memcached
  namespace: monsoon3
  labels:
    system: openstack
    component: cache
  annotations:
    kubernetes.io/change-cause: {{cluster_config['cluster.deployment.reason']}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: memcached
  template:
    metadata:
      labels:
        name: memcached
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: memcached
          image: memcached
          imagePullPolicy: Always
          ports:
            - name: memcache
              containerPort: {{cluster_config['memcache.port.public']}}
        - name: metrics
          image: prom/memcached-exporter:master
          ports:
            - name: metrics
              containerPort: {{cluster_config['memcache.port.metrics']}}

