kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: designate-api
  namespace: monsoon3
  labels:
    system: openstack
    component: designate
  annotations:
    kubernetes.io/change-cause: {{cluster_config['cluster.deployment.reason']}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      app: designate-api
  template:
    metadata:
      labels:
        app: designate-api
      annotations:
        checksum/designate.etc: {{checksums['designate-etc-configmap.yaml']}}
        checksum/designate.bin: {{checksums['designate-bin-configmap.yaml']}}
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: designate-api
          image: {{cluster_config['cluster.image.repository']}}/{{cluster_config['cluster.image.namespace']}}/ubuntu-source-designate-api-m3:{{cluster_config['image.version.designate.api.m3']}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - designate-api-start
          livenessProbe:
            httpGet:
              path: /
              port: {{cluster_config['designate.api.port.internal']}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: designate.sentry.dsn
          ports:
            - name: designate-api
              containerPort: {{cluster_config['designate.api.port.internal']}}
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
            - mountPath: /designate-etc
              name: designate-etc
            - mountPath: /container.init
              name: container-init
        - name: statsd
          image: prom/statsd-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{cluster_config['designate.port.metrics']}}
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
        - name: designate-etc
          configMap:
            name: designate-etc
        - name: container-init
          configMap:
            name: designate-bin
