kind: Service
apiVersion: v1

metadata:
  name: designate-api
  namespace: monsoon3
  labels:
    system: openstack
    component: designate
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{cluster_config['designate.port.metrics']}}"
spec:
  type: NodePort
  selector:
    app: designate-api
  ports:
    - name: designate-api
      port: {{cluster_config['designate.api.port.internal']}}

