---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-bin
  labels:
    system: openstack
    component: configuration

data:
  pgbouncer-start: |
    {{config['postgres/pgbouncer-start']}}
  common.sh: |
    {{config['common.sh']}}


