kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceilometer-rabbitmq-pvclaim
  namespace: ceilometer
  labels:
    system: openstack
    component: metering

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
