kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: monasca-es-data1-pvclaim
  namespace: monasca
  labels:
    system: openstack
    component: monitoring

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
