kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: monasca-influxdb-pvclaim
  namespace: monasca
  labels:
    system: openstack
    component: monitoring

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
