kind: ReplicationController
apiVersion: v1

metadata:
  name: monasca-logstash-persister
  namespace: monasca
  labels:
    system: openstack
    service: monitoring

spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: monasca-logstash-persister
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
      containers:
        - name: monasca-logstash-persister
          image: docker.mo.sap.corp/monasca/monasca-logstash:latest
          imagePullPolicy: Always
          command:
            - dumb-init
          args:
            - /openstack-kube/openstack-kube/scripts/monasca-logstash_start
          ports:
            - name: kafkacluster
              containerPort: {{cluster_config['monasca.kafka.port.internal']}} 
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
          env:
          - name: LOGSTASH_TYPE
            value: "persister"
          - name: MONASCA_KAFKA_PORT_INTERNAL
            value: "{{cluster_config['monasca.kafka.port.internal']}}"
          - name: MONASCA_ZOOKEEPER_PORT_INTERNAL
            value: "{{cluster_config['monasca.zookeeper.port.internal']}}"
          lifecycle:
            preStop:
              exec:
                command: ["/stop.sh"]

