kind: ReplicationController
apiVersion: v1

metadata:
  name: monasca-log-api
  namespace: monasca
  labels:
    system: openstack
    service: monitoring

spec:
  replicas: 1 
  template:
    metadata:
      labels:
        component: monasca-log-api
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{cluster_config['cluster.configuration.repository']}}
            revision: {{cluster_config['cluster.configuration.revision']}}
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: cluster-secret
          secret:
            secretName: cluster-secret
      containers:
        - name: monasca-log-api
          image: docker.mo.sap.corp/monasca/monasca-log-api:latest
          imagePullPolicy: Always
          command:
            - dumb-init
          args:
            - /openstack-kube/openstack-kube/scripts/monasca/log-api_start
          ports:
            - name: logapi
              containerPort: {{cluster_config['monasca.log.api.port.public']}}
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /cluster-config
              name: cluster-config
            - mountPath: /cluster-secret
              name: cluster-secret
          env:
          - name: MONASCA_KAFKA_PORT_INTERNAL
            value: "{{cluster_config['monasca.kafka.port.internal']}}"
