apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: monasca-log-api
  namespace: monasca

spec:
  tls:
     - secretName: tls-{{cluster_config['monasca.log.api.endpoint.host.public'].replace(".","-")}}
       hosts: [{{cluster_config['monasca.log.api.endpoint.host.public']}}]
  rules:
    - host: {{cluster_config['monasca.log.api.endpoint.host.public']}}
      http:
        paths:
        - path: /
          backend:
            serviceName: monasca-log-api
            servicePort: {{cluster_config['monasca.log.api.port.public']}}

