kind: Service
apiVersion: v1
metadata:
  name: monasca-log-api
  namespace: monasca
  labels:
    system: openstack
    service: monitoring
spec:
  selector:
    component: monasca-log-api
  ports:
    - port: {{cluster_config['monasca.log.api.port.public']}}
