kind: Service
apiVersion: v1

metadata:
  name: ironic-pxe
  namespace: monsoon3
  labels:
    system: openstack
    component: ironic
spec:
  type: NodePort
  selector:
    name: ironic-pxe
  ports:
    - name: ironic-pxe
      protocol: UDP
      port: {{cluster_config['ironic.pxe.port.public']}}
