kind: Service
apiVersion: v1

metadata:
  name: designate-mdns
  namespace: monsoon3
  labels:
    system: openstack
    component: designate

spec:
  type: NodePort
  selector:
    app: designate-mdns
  ports:
    - name: designate-mdns-tcp
      protocol: TCP
      port: {{cluster_config['designate.mdns.port.public']}}
    - name: designate-mdns-udp
      protocol: UDP
      port: {{cluster_config['designate.mdns.port.public']}}
  externalIPs: [{{cluster_config['designate.mdns.external.ip']}}]
